# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      15

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle/Entity/App_user
                property: username
      #  in_memory:
       #     memory: 
       #         users:
       #             ryan:
       #            admin:
       #                 password: 'pass'
        #                roles: 'ROLE_ADMIN'

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            
            form_login:
                login_path: login
                check_path: login
                failure_path: home
                target_path_parameter: data

                
    access_control:

    - { path: ^/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/form, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }  #ROLE_ADMIN

    


